# Generated by Django 2.0.5 on 2018-05-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170122_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчиков', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
